"""create customers, rates, tariffs

Revision ID: ae29ad8166a1
Revises: 
Create Date: 2025-10-02 10:54:29.337165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae29ad8166a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_port', sa.String(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('container_type', sa.String(), nullable=False),
    sa.Column('freight_usd', sa.Float(), nullable=False),
    sa.Column('othc_aud', sa.Float(), nullable=False),
    sa.Column('doc_aud', sa.Float(), nullable=False),
    sa.Column('cmr_aud', sa.Float(), nullable=False),
    sa.Column('ams_usd', sa.Float(), nullable=False),
    sa.Column('lss_usd', sa.Float(), nullable=False),
    sa.Column('dthc', sa.String(), nullable=False),
    sa.Column('free_time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_port', sa.String(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('container_type', sa.String(), nullable=False),
    sa.Column('freight_usd', sa.Float(), nullable=False),
    sa.Column('othc_aud', sa.Float(), nullable=False),
    sa.Column('doc_aud', sa.Float(), nullable=False),
    sa.Column('cmr_aud', sa.Float(), nullable=False),
    sa.Column('ams_usd', sa.Float(), nullable=False),
    sa.Column('lss_usd', sa.Float(), nullable=False),
    sa.Column('dthc', sa.String(), nullable=False),
    sa.Column('free_time', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('freight_usd >= 0', name='ck_freight_nonneg'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'load_port', 'destination_port', 'container_type', name='uq_customer_lane_container')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_table('tariffs')
    op.drop_table('customers')
    # ### end Alembic commands ###
